import os

VERSION = "1.5.0"

DEFAULT_PROMPT = """
Analyze this page and extract ALL tables you see.
Even if the table looks like a screenshot or an embedded image, extract it.
Return results strictly in Markdown format.
Do not include any introductory text, titles outside the table, or comments.
If no tables are found, return an empty string.
""".strip()

TEXTS = {
    "EN": {
        "title": "PDF to EXCEL/CSV/MD AI Extractor",
        "config_section": " 1. CONFIGURATION ",
        "api_key": "API Key:",
        "save_key": "Save Key",
        "paste_key": "Paste",
        "clear_key": "Clear",
        "get_key": "Get your free API key at Google AI Studio",
        "pdf_selection": " 2. PDF SELECTION ",
        "select_files": "Select files to process:",
        "add_files": "+ Add Files",
        "clear": "🗑 Clear",
        "output_config": " 3. OUTPUT CONFIGURATION ",
        "output_folder": "Output Folder:",
        "browse": "Browse...",
        "excel_name": "Excel Name:",
        "csv_name": "CSV Name:",
        "md_name": "MD Name:",
        "options_section": " 4. OPTIONS ",
        "opt_excel": "Excel (.xlsx)",
        "opt_md": "Markdown (.md)",
        "opt_csv": "CSV (.csv)",
        "opt_normalize": "Normalize Data",
        "start_btn": " START EXTRACTION ",
        "status_log": " STATUS LOG ",
        "edit_prompt": "Edit Prompt",
        "ilovepdf": "Other PDF tools (iLovePDF)",
        "language": "Language:",
        "save": "Save",
        "reset": "Reset",
        "cancel": "Cancel",
        "prompt_editor_title": "Prompt Editor",
        "success": "Success",
        "warning": "Warning",
        "error": "Error",
        "key_saved": "API Key saved to api_key.env",
        "no_key": "Gemini API Key is required.",
        "key_length": "Incorrect API Key length. The key must be 39 characters long.",
        "no_files": "Please add at least one PDF file.",
        "process_finished": "Process Finished",
        "process_success": "The extraction process has completed successfully!",
        "process_error": "Process finished with errors.",
        "all_tasks_done": "SYSTEM: All tasks completed.",
        "analyzing_page": "    - Analyzing page {}...",
        "working_on": "Working on: {}",
        "done": "DONE: {}",
        "skip": "SKIP: No tables in {}",
        "saved_md": "  + Saved MD: {}",
        "saved_csv": "  + Saved CSV: {}",
        "files_added": "Added {} new files.",
        "files_cleared": "File selection cleared.",
        "output_path_set": "Output path: {}",
        "fatal_error": "The process encountered a fatal error",
        "quota_error": "The daily API limit has been exceeded (Code 429).",
        "api_leaked": "The API key has been leaked, create a new one (Code 403).",
        "api_error": "The API key entered is incorrect (Code 400). Please verify it and try again."
    },
    "ES": {
        "title": "Extractor de Tablas PDF con IA",
        "config_section": " 1. CONFIGURACIÓN ",
        "api_key": "Clave API:",
        "save_key": "Guardar",
        "paste_key": "Pegar",
        "clear_key": "Borrar",
        "get_key": "Obtén tu clave API gratis en Google AI Studio",
        "pdf_selection": " 2. SELECCIÓN DE PDF ",
        "select_files": "Selecciona archivos para procesar:",
        "add_files": "+ Añadir Archivos",
        "clear": "🗑 Limpiar",
        "output_config": " 3. CONFIGURACIÓN DE SALIDA ",
        "output_folder": "Carpeta de Salida:",
        "browse": "Buscar...",
        "excel_name": "Nombre Excel:",
        "csv_name": "Nombre CSV:",
        "md_name": "Nombre MD:",
        "options_section": " 4. OPCIONES ",
        "opt_excel": "Excel (.xlsx)",
        "opt_md": "Markdown (.md)",
        "opt_csv": "CSV (.csv)",
        "opt_normalize": "Normalizar Datos",
        "start_btn": " INICIAR EXTRACCIÓN ",
        "status_log": " REGISTRO DE ESTADO ",
        "edit_prompt": "Editar Prompt",
        "ilovepdf": "Otras herramientas PDF (iLovePDF)",
        "language": "Idioma:",
        "save": "Guardar",
        "reset": "Reiniciar",
        "cancel": "Cancelar",
        "prompt_editor_title": "Editor de Prompt",
        "success": "Éxito",
        "warning": "Advertencia",
        "error": "Error",
        "key_saved": "Clave API guardada en api_key.env",
        "no_key": "Se requiere la clave API de Gemini.",
        "key_length": "Longitud de API incorrecta. La clave debe tener 39 caracteres.",
        "no_files": "Por favor, añade al menos un archivo PDF.",
        "process_finished": "Proceso Finalizado",
        "process_success": "¡El proceso de extracción ha finalizado con éxito!",
        "process_error": "Proceso finalizado con errores.",
        "all_tasks_done": "SISTEMA: Todas las tareas completadas.",
        "analyzing_page": "    - Analizando página {}...",
        "working_on": "Trabajando en: {}",
        "done": "LISTO: {}",
        "skip": "OMITIR: No hay tablas en {}",
        "saved_md": "  + MD Guardado: {}",
        "saved_csv": "  + CSV Guardado: {}",
        "files_added": "Añadidos {} nuevos archivos.",
        "files_cleared": "Selección de archivos limpiada.",
        "output_path_set": "Ruta de salida: {}",
        "fatal_error": "El proceso encontró un error fatal",
        "quota_error": "Se ha excedido el límite de la API diario (Código 429).",
        "api_leaked": "La clave API ha sido filtrada, cree una nueva (Código 403).",
        "api_error": "La clave API ingresada no es correcta (Código 400). Por favor, verifíquela e inténtelo de nuevo."
    }
}                   
